# frozen_string_literal: true

source 'https://rubygems.org'
ruby '3.3.9'

gem 'grape'
gem 'grape-entity'
gem 'listen'
gem 'newrelic_rpm'
gem 'pg'

gem 'rails', '~> 7.2'
gem 'puma'
gem 'net-http'

gem 'googlecharts'

gem 'cssbundling-rails'
gem 'sdoc', group: :doc
gem 'propshaft'
gem 'terminal-table'
gem 'trueskill'
gem 'will_paginate'

gem 'jsbundling-rails'
gem 'bootsnap', require: false

group :development do
  gem 'active_record_doctor'
  gem 'web-console'
end

group :development, :test do
  gem 'capybara'
  gem 'selenium-webdriver'

  gem 'factory_bot_rails'
  gem 'observer'
  gem 'faker'
  gem 'pry'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'timecop'
end
