# frozen_string_literal: true

source 'https://rubygems.org'
ruby '3.1.2'

gem 'grape'
gem 'grape-entity'
gem 'listen'
gem 'newrelic_rpm'
gem 'pg'

gem 'rails'
gem 'puma'
gem 'net-http'

gem 'googlecharts'

gem 'sass-rails'
gem 'sdoc', group: :doc
gem 'sprockets-rails'
gem 'terminal-table'
gem 'trueskill'
gem 'will_paginate'

gem 'webpacker', '~> 6.0.0.rc.6'
gem 'bootsnap', require: false

group :development do
  gem 'active_record_doctor'
  gem 'web-console'
end

group :development, :test do
  gem 'capybara'
  gem 'selenium-webdriver'

  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'timecop'
end
