#!/usr/bin/env bash
echo "--- [script:bootstrap]"

echo "--- Brewing"
brew bundle

echo "--- Mising"
mise trust --yes --quiet
mise install
eval "$(mise hook-env)"

echo "--- Bundling"
bundler_version=$(cat ./.bundler-version)
gem install --no-document "bundler:$bundler_version"
bundle config set --local build.pg "--with-pg-config='$(mise where postgres)/bin/pg_config'"
bundle install

echo "--- Yarning"
yarn install

export DISABLE_DATABASE_ENVIRONMENT_CHECK=1

# don't reset db; most people run a prod db locally
bin/rails db:create db:migrate
