#!/usr/bin/env bash

if [ ! -f .env ]; then
  cp .env.example .env
fi

brew bundle

pushd analyser
  ./script/bootstrap.sh
popd

pushd brain
  ./script/bootstrap
popd

pushd players
  ./script/bootstrap
popd
